name: Build

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
  pull_request:
    branches: [master]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Library
        run: yarn build
      - name: Run Tests and Get Coverage
        run: yarn coverage
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
